language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true

before_install:
  - chmod +x travis-init.sh

install: ./travis-init.sh

script:
  - phpunit --coverage-text